opt_in_rules: 
  - sorted_imports
  - empty_count
  - redundant_type_annotation
  - trailing_closure
  - unused_import
  - implicit_return
  - multiline_function_chains
disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - identifier_name
  - todo
  - nesting
excluded: 
  - Pods

function_body_length:
    warning: 300
    error: 500

type_body_length:
    warning: 450
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 30
    error: 45

line_length:
    warning: 250
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
