opt_in_rules: 
  - sorted_imports
  - empty_count
  - redundant_type_annotation
  - trailing_closure
  - unused_import
  - implicit_return
  - multiline_function_chains
  - anyobject_protocol
  - array_init
  - attributes 
  - closure_end_indentation
  - closure_spacing
  - reduce_boolean
  - file_types_order
  - type_contents_order
disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - todo
  - nesting
excluded: 
  - Pods

function_body_length:
    warning: 300
    error: 500

type_body_length:
    warning: 450
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 30
    error: 45

line_length:
    warning: 250
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
    - i
    - v

custom_rules:
  comments_space: # From https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  explicit_failure_calls:
      name: “Avoid asserting ‘false’”
      regex: ‘((assert|precondition)\(false)’
      message: “Use assertionFailure() or preconditionFailure() instead.”
      severity: warning
  multiple_empty_lines:
     name: "Multiple Empty Lines"
     regex: '((?:\s*\n){3,})'
     message: "There are too many line breaks"
     severity: error
