platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 2.6.0'
pod 'SDWebImage', '~> 3.7.3'
pod 'GDataXML-HTML', '~> 1.3.0'
pod 'TSMessages', '~> 0.9.12'
pod 'CrittercismSDK', '~> 5.4.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.12'
pod 'NKOColorPickerView', '~> 0.5'
pod 'FastSocket', '~> 1.3'
