platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'GDataXML-HTML', '~> 1.2.0'
pod 'TSMessages', '~> 0.9.10'
pod 'CrittercismSDK', '~> 5.0.4'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.9'
pod 'NKOColorPickerView', '~> 0.2'
pod 'FastSocket', '~> 1.2'
