platform :ios, '7.0'
pod 'AFNetworking', '~> 2.3'
pod 'SDWebImage', '~> 3.6'
pod 'GDataXML-HTML', '~> 1.1.0'
pod 'TSMessages', '~> 0.9.9'
pod 'CrittercismSDK', '~> 4.3.4'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.7'
pod 'NKOColorPickerView', '~> 0.2'
pod 'FastSocket', '~> 1.2'
