# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
 
platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "openHAB.xcworkspace", scheme: "openHABUITests")
  end

  desc "Build beta"
  lane :beta do

    # ensure you are in master branch
    # ensure_git_branch

    # ensure that master branch is clean
    ensure_git_status_clean

    # check the semantic parameter entered
    if !lane[:bump]
    raise "No bump type defined! Use one of: patch | minor | major".red
    end

#changelog = prompt(
#    text: "Changelog: ",
#    multi_line_end_keyword: "END"
#    )

    # get the last commit comments from Git history
    # and creates our changelog
    comments = changelog_from_git_commits(
    between: [last_git_tag, "HEAD"],
    pretty: "- %s",
    date_format: "short",
    match_lightweight_tag: false,
    merge_commit_filtering: "exclude_merges"
    )

    type = lane[:bump]

    increment_version_number(
        bump_type: type,
        xcodeproj: "openHAB.xcodeproj"
    )
    increment_build_number(xcodeproj: "openHAB.xcodeproj")
    commit_version_bump(xcodeproj: "openHAB.xcodeproj")
    add_git_tag
    push_to_git_remote
    build_app(scheme: "openHAB")
    upload_to_testflight(
        distribute_external: true,
        notify_external_testers: true,
        changelog: changelog,
        groups: ["Beta Testers"]
    )
  end

end
