# Uncomment the lines below you want to change by removing the # in the beginning

#A list of devices you want to take the screenshots from
devices([
    "iPhone 11 Pro Max",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPhone 8 Plus",
    "iPad Pro (12.9-inch) (3rd generation)"
])

#languages([
#    "en-US",
#    "de-DE"
#])

launch_arguments([
  "-demomode true -iconType 0"
])

# The name of the scheme which contains the UI Tests
scheme("openHABUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots true
skip_open_summary true

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# Choose which project/workspace to use
workspace "./openHAB.xcworkspace"

# For more information about all available options run
# fastlane action snapshot
