name: Run Unit Tests Update

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install --redownload
      - name: List available simulators
        run: xcrun simctl list
      - name: Boot Simulator
        run: |
          xcrun simctl boot "51C4E281-1F04-4BE9-9392-8499B31B9351"
      - name: List available simulators
        run: xcrun simctl list

      - name: Fastlane unit tests
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
        run: bundle exec fastlane unittests
